---

# common
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: user

  tasks:

  - name: Install ssh key into all hosts
    authorized_key: user=user
                    key="{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}"
                    state=present

  - name: Install git into all hosts
    action: apt name=git state=installed update_cache=yes

# balancer
- hosts: balancer
  sudo: yes

  tasks:

  - name: Install socat
    apt: pkg={{ item }} state=latest
    with_items:
    - socat


# webhost
- hosts: webhost
  sudo: yes
  serial: 2

  pre_tasks:

  - name: Set web host into maintenance mode
    shell: echo "disable server {{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: groups.balancer


  tasks:

  - name: Remove current website
    file: path=/usr/share/nginx/html/ state=absent

  - name: Deploy new website
    git: repo=https://github.com/paverher/verysimplewebpage.git
         dest=/usr/share/nginx/html/

  post_tasks:

  - name: Set web host into active mode
    shell: echo "enable server {{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: groups.balancer


