---

# common
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: user

  tasks:

  - name: install ssh key
    authorized_key: user=user
                    key="{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}"
                    state=present

  - name: install git
    action: apt name=git state=installed update_cache=yes

# balancer
- hosts: balancer
  sudo: yes

  tasks:

  - name: Download and install haproxy and socat
    apt: pkg={{ item }} state=latest
    with_items:
    - haproxy
    - socat

  - name: Enable HAProxy
    lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
    notify: restart haproxy

  - name: Configure the haproxy cnf file with hosts
    template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    notify: restart haproxy

  handlers:

  - name: restart haproxy
    service: name=haproxy state=restarted


# webhost
- hosts: webhost
  sudo: yes
  serial: 1

  pre_tasks:

  - name: disable node in haproxy
    shell: echo "disable server {{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: groups.balancer


  tasks:

  - name: remove current website content
    file: path=/usr/share/nginx/html/ state=absent

  - name: deploy new website content
    git: repo=https://github.com/paverher/verysimplewebpage.git
         dest=/usr/share/nginx/html/

  post_tasks:

  - name: enable node in haproxy
    shell: echo "enable server {{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: groups.balancer


